name: Wallets Release to Test environment Workflow
on:
  pull_request:

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  pull-requests: write
  statuses: read

jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Test
    runs-on: ubuntu-latest
    environment: Preview
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Setup Node
      uses: "./.github/actions/setup_node"
    - name: Install Dependencies
      uses: "./.github/actions/npm_install_from_cache"
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: preview
        CROWDIN_WALLETS_API_KEY: ${{ secrets.CROWDIN_WALLETS_API_KEY }}
        DATADOG_APPLICATION_ID: ${{ vars.DATADOG_APPLICATION_ID }}
        IS_GROWTHBOOK_ENABLED: ${{ vars.IS_GROWTHBOOK_ENABLED }}
        DATADOG_CLIENT_TOKEN: ${{ vars.DATADOG_CLIENT_TOKEN }}
        DATADOG_CLIENT_TOKEN_LOGS: ${{ vars.DATADOG_CLIENT_TOKEN_LOGS }}
        DATADOG_SESSION_REPLAY_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_REPLAY_SAMPLE_RATE }}
        DATADOG_SESSION_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_SAMPLE_RATE }}
        DATADOG_SESSION_SAMPLE_RATE_LOGS: ${{ vars.DATADOG_SESSION_SAMPLE_RATE_LOGS }}
        GD_API_KEY: ${{ secrets.GD_API_KEY }}
        GD_APP_ID: ${{ secrets.GD_APP_ID }}
        GD_CLIENT_ID: ${{ secrets.GD_CLIENT_ID }}
        RUDDERSTACK_KEY: ${{ vars.RUDDERSTACK_KEY }}
        GROWTHBOOK_CLIENT_KEY: ${{ vars.GROWTHBOOK_CLIENT_KEY }}
        GROWTHBOOK_DECRYPTION_KEY: ${{ vars.GROWTHBOOK_DECRYPTION_KEY }}
        REF_NAME: ${{ github.ref_name }}
        REMOTE_CONFIG_URL: ${{ vars.REMOTE_CONFIG_URL }}
    # - name: Run tests
    #   run: npm test
    - name: Publish to cloudflare pages (test)
      id: deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy dist/ --project-name=deriv-wallets --branch=test
        workingDirectory: packages/core

    - name: Comment PR with deployment URL
      uses: actions/github-script@v5
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const deploymentUrl = process.env.DEPLOYMENT_URL;
          const prNumber = context.payload.pull_request.number;
          const message = `🚀 Deploy preview ready! [${deploymentUrl}](${deploymentUrl})`;

          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: message
          });
      env:
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
